### ISSUE TITLE
Is this repository of any use for sharelex.org?

### ISSUE THREAD

**Issue by bzg** [ShareLex/static#1]
I'm not sure what purpose this repository serves.

Can @hauleth @albanlv @fcarrega let me know?

If this is not used anymore, can we safely delete it?

Thanks!

**Comment by fcarrega** [comment]
Seems that it contains the static pages accesible here : pages.sharelex.org

Ex. : http://pages.sharelex.org/about/

**Comment by bzg** [comment]
Merci. Sigh. I only realize the page module has never been used...

I started to edit the pages here: http://www.sharelex.org/admin/plugins/pages

**Comment by jeanparpaillon** [comment]
These pages are served on 'static.sharelex.org'
